### ISSUE TITLE
PG::QueryCanceled: ERROR: canceling statement due to statement timeout

### ISSUE THREAD

**Issue by leoplct** [ankane/strong_migrations#143]
I am receving this error for other queries. How can I set the 10 sec timeout only when running migrations?

PG::QueryCanceled: ERROR: canceling statement due to statement timeout

**Comment by bheemreddy181** [comment]
please read https://github.com/ankane/strong_migrations#migration-timeouts

**Comment by leoplct** [comment]
Ok, thanks. So solution is to set both

this for migration
```
StrongMigrations.lock_timeout = 10.seconds
StrongMigrations.statement_timeout = 1.hour
```
this for all queries

```
production:
  adapter: postgresql
  encoding: unicode
  connect_timeout: 5
  variables:
    statement_timeout: 0 
    lock_timeout: 0
```
