### ISSUE TITLE
Statement timeout is ignored (v2)

### ISSUE THREAD

**Issue by feliperaul** [ankane/strong_migrations#297]
First of all, can't open an issue without first praising @ankane for such a great gem. Thank you so much. 

This has already been reported in #201 and it also hit us today.

Even tough we have `StrongMigrations.statement_timeout = 1.hour` set in an initializer, our migration (that had a large `update_all`) was timing out with `PG::QueryCanceled: ERROR:  canceling statement due to statement timeout` in 15 seconds, which is the time we set in database.yml.

I timed (because we ran the migration multiple times) and they all timed out at 15s, consistently, which is set in our database.yml:

```
production:
  adapter: postgresql
  database: xx
  username: xx
  password: xx
  encoding: unicode
  host: localhost
  port: 5432
  connect_timeout: 5
  variables:
    statement_timeout: 15s
    lock_timeout: 10s
```

This project is self hosted and postgres is managed by us via docker, so maybe it's easier to debug this time?

What I found weird is that, even if we changed that statement_timeout to something much larger (like 100s), it was still timing out at 15s.

If we run SHOW statement_timeout inside psql, we get `0` back.

Thanks in advance for any hints!
